### ISSUE TITLE
[BUG] `read_redcap()` fails to parse labels with no whitespace between raw values and labels 

### ISSUE THREAD

**Issue by camcaan** [CHOP-CGTInformatics/REDCapTidieR#128]
# Expected Behavior
I wanted to import the data in REDCap as a supertibble

# Current Behavior
It gives me error : Caused by error in `gsub()`:
! result string is too long

## How to Reproduce the Bug:
Backtrace:
  1. REDCapTidieR::read_redcap(nitrate_uri, nitrate_token)
  8. REDCapR::redcap_metadata_read(...)
  9. REDCapR:::kernel_api(redcap_uri, post_body, config_options)
 10. httr::POST(...)
 17. global redactor(.resp)
 18. purrr::reduce(...)
       at REDCapTidieR/httptest/redact.R:19:2
 19. purrr:::reduce_impl(.x, .f, ..., .init = .init, .dir = .dir)
 20. fn(out, elt, ...)
 21. httptest::gsub_response(.x, real_creds[.y], fake_creds[.y])
 22. httptest::within_body_text(response, replacer)
 23. httptest (local) FUN(old)
 24. base::gsub(pattern, replacement, x, ...)

**Comment by ezraporter** [comment]
Hi @camcaan thanks for the bug report! It looks like you are somehow triggering a bit a code that's only supposed to run in our test suite which is causing the error. Can you provide some additional information to help me figure out why it's being triggered?

1. The version of `REDCapTidieR` you're using and whether you installed from CRAN or our github
2. The result of running `sessionInfo()` in a session where you encounter the bug

**Comment by camcaan** [comment]
Hi thanks for the reply. I installed the package from CRAN. 
It could be something very simple but I am using REDCap and REDCapTidier for the first time.
Gives me a different error now:
Error in `parse_labels()`:                                                                                                                         
! Cannot parse the select_choices_or_calculations field from REDCap metadata. This may happen if there
  is a pipe character `|` inside the label: 1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour
  metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported


**session Infor:**
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] REDCapTidieR_0.2.0.9000 readr_2.1.3             httr_1.4.4             

loaded via a namespace (and not attached):
 [1] lobstr_1.1.2      pillar_1.8.1      compiler_4.2.1    tools_4.2.1       digest_0.6.30     bit_4.0.4        
 [7] jsonlite_1.8.2    evaluate_0.17     lifecycle_1.0.3   tibble_3.1.8      checkmate_2.1.0   pkgconfig_2.0.3  
[13] rlang_1.0.6       DBI_1.1.3         cli_3.4.1         rstudioapi_0.14   curl_4.3.3        yaml_2.3.6       
[19] parallel_4.2.1    xfun_0.34         fastmap_1.1.0     stringr_1.4.1     dplyr_1.0.10      withr_2.5.0      
[25] knitr_1.40        REDCapR_1.1.0     htmlwidgets_1.6.1 generics_0.1.3    vctrs_0.4.2       hms_1.1.2        
[31] bit64_4.0.5       tidyselect_1.2.0  glue_1.6.2        R6_2.5.1          fansi_1.0.3       vroom_1.6.0      
[37] rmarkdown_2.17    tidyr_1.2.1       purrr_0.3.5       tzdb_0.3.0        magrittr_2.0.3    backports_1.4.1  
[43] ellipsis_0.3.2    htmltools_0.5.4   assertthat_0.2.1  formattable_0.2.1 utf8_1.2.2        stringi_1.7.8    
[49] crayon_1.5.2     

**Backtrace:**

Error in `parse_labels()`:
! Cannot parse the select_choices_or_calculations field from REDCap metadata. This may happen if there
  is a pipe character `|` inside the label: 1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour
  metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported
---
Backtrace:
    ▆
 1. └─REDCapTidieR::read_redcap(url, token)
 2.   └─REDCapTidieR:::update_field_names(db_metadata)
 3.     └─REDCapTidieR:::parse_labels(out$select_choices_or_calculations[i])
 4.       └─cli::cli_abort(...)
 5.         └─rlang::abort(...)

**Comment by skadauke** [comment]
Hi Kamran, can you install the newest version from GitHub and try again?
________________________________
From: Kamran Khan ***@***.***>
Sent: Tuesday, February 14, 2023 11:35 AM
To: CHOP-CGTInformatics/REDCapTidieR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External]Re: [CHOP-CGTInformatics/REDCapTidieR] [BUG] (Issue #128)


Hi thanks for the reply. I installed the package from CRAN.
It could be something very simple but I am using REDCap and REDCapTidier for the first time.
Gives me a different error now:
Error in parse_labels():
! Cannot parse the select_choices_or_calculations field from REDCap metadata. This may happen if there
is a pipe character | inside the label: 1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour
metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported

session Infor:
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] REDCapTidieR_0.2.0.9000 readr_2.1.3 httr_1.4.4

loaded via a namespace (and not attached):
[1] lobstr_1.1.2 pillar_1.8.1 compiler_4.2.1 tools_4.2.1 digest_0.6.30 bit_4.0.4
[7] jsonlite_1.8.2 evaluate_0.17 lifecycle_1.0.3 tibble_3.1.8 checkmate_2.1.0 pkgconfig_2.0.3
[13] rlang_1.0.6 DBI_1.1.3 cli_3.4.1 rstudioapi_0.14 curl_4.3.3 yaml_2.3.6
[19] parallel_4.2.1 xfun_0.34 fastmap_1.1.0 stringr_1.4.1 dplyr_1.0.10 withr_2.5.0
[25] knitr_1.40 REDCapR_1.1.0 htmlwidgets_1.6.1 generics_0.1.3 vctrs_0.4.2 hms_1.1.2
[31] bit64_4.0.5 tidyselect_1.2.0 glue_1.6.2 R6_2.5.1 fansi_1.0.3 vroom_1.6.0
[37] rmarkdown_2.17 tidyr_1.2.1 purrr_0.3.5 tzdb_0.3.0 magrittr_2.0.3 backports_1.4.1
[43] ellipsis_0.3.2 htmltools_0.5.4 assertthat_0.2.1 formattable_0.2.1 utf8_1.2.2 stringi_1.7.8
[49] crayon_1.5.2

Backtrace:

Error in parse_labels():
! Cannot parse the select_choices_or_calculations field from REDCap metadata. This may happen if there
is a pipe character | inside the label: 1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour
metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported

Backtrace:
▆

  1.  └─REDCapTidieR::read_redcap(url, token)
  2.  └─REDCapTidieR:::update_field_names(db_metadata)
  3.

└─REDCapTidieR:::parse_labels(out$select_choices_or_calculations[i])



  4.

  └─cli::cli_abort(...)



  5.

    └─rlang::abort(...)



—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTInformatics%2FREDCapTidieR%2Fissues%2F128%23issuecomment-1430041147&data=05%7C01%7Ckadaukes%40chop.edu%7C70b702129346476efc3908db0ea98f63%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119893655271671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wN7s6rokTWMn44XCM90T9ZDlg89XylhMONmFsPTtEVA%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWUOPYQ6GOJSTNDRFCDWXOX65ANCNFSM6AAAAAAU3S7XQA&data=05%7C01%7Ckadaukes%40chop.edu%7C70b702129346476efc3908db0ea98f63%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119893655271671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rXh9wmI8NVPQU8OedeSN1X35hitdOb42JDsJ52OiMBU%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by skadauke** [comment]
Have you restarted R after installing the GitHub version?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Kamran Khan ***@***.***>
Sent: Tuesday, February 14, 2023 11:51:57 AM
To: CHOP-CGTInformatics/REDCapTidieR ***@***.***>
Cc: Stephan Kadauke ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [CHOP-CGTInformatics/REDCapTidieR] [BUG] (Issue #128)


I installed from GitHub and updated the dependent packages as well.
REDCapTidieR_0.2.0.9001
I think it might be something to do with the columns names in the database.

so the error is

nitrate <- read_redcap(url, token)
Error in parse_labels():
! Cannot parse the select_choices_or_calculations field from REDCap metadata. This may happen if there
is a pipe character | inside the label: 1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour
metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported

________________________________

Backtrace:
▆

  1.  └─REDCapTidieR::read_redcap(url, token)
  2.  └─REDCapTidieR:::update_field_names(db_metadata)
  3.

└─REDCapTidieR:::parse_labels(out$select_choices_or_calculations[i])



  4.

  └─cli::cli_abort(...)



  5.

    └─rlang::abort(...)



sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] REDCapTidieR_0.2.0.9001 readr_2.1.4 httr_1.4.4

loaded via a namespace (and not attached):
[1] Rcpp_1.0.10 tidyr_1.3.0 prettyunits_1.1.1 ps_1.7.1 rprojroot_2.0.3 assertthat_0.2.1
[7] digest_0.6.31 utf8_1.2.3 mime_0.12 R6_2.5.1 REDCapR_1.1.0 backports_1.4.1
[13] evaluate_0.20 pillar_1.8.1 rlang_1.0.6 curl_5.0.0 rstudioapi_0.14 miniUI_0.1.1.1
[19] urlchecker_1.0.1 callr_3.7.3 checkmate_2.1.0 rmarkdown_2.20 lobstr_1.1.2 desc_1.4.2
[25] devtools_2.4.5 stringr_1.5.0 htmlwidgets_1.6.1 bit_4.0.5 shiny_1.7.4 compiler_4.2.1
[31] httpuv_1.6.8 xfun_0.37 pkgconfig_2.0.3 pkgbuild_1.4.0 htmltools_0.5.4 tidyselect_1.2.0
[37] tibble_3.1.8 fansi_1.0.4 crayon_1.5.2 dplyr_1.1.0 tzdb_0.3.0 withr_2.5.0
[43] later_1.3.0 jsonlite_1.8.4 xtable_1.8-4 formattable_0.2.1 lifecycle_1.0.3 DBI_1.1.3
[49] magrittr_2.0.3 cli_3.6.0 stringi_1.7.12 vroom_1.6.1 cachem_1.0.6 remotes_2.4.2
[55] fs_1.6.1 promises_1.2.0.1 ellipsis_0.3.2 generics_0.1.3 vctrs_0.5.2 tools_4.2.1
[61] bit64_4.0.5 glue_1.6.2 purrr_1.0.1 hms_1.1.2 processx_3.7.0 pkgload_1.3.2
[67] parallel_4.2.1 fastmap_1.1.0 yaml_2.3.7 sessioninfo_1.2.2 memoise_2.0.1 knitr_1.42
[73] usethis_2.1.6 profvis_0.3.7

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTInformatics%2FREDCapTidieR%2Fissues%2F128%23issuecomment-1430064349&data=05%7C01%7Ckadaukes%40chop.edu%7Cc430eccb763a4e59f98008db0eabcab2%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119903224275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dgVRIUpU%2FQzuezE0MxuDR%2FmiHWaw33QTa0pPeJ6xxgM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWT6V6JYUFN66VFSYRLWXOZ23ANCNFSM6AAAAAAU3S7XQA&data=05%7C01%7Ckadaukes%40chop.edu%7Cc430eccb763a4e59f98008db0eabcab2%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119903224275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tOcqcen0PUWjr6lXjjZ017XQpCBNExVCd5fuUIzMUC8%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by camcaan** [comment]
Yes, I did restarted R session and the following same error.
Will it still work if the column names have special characters?
Error in `parse_labels()`:                                                                                                                         
! Cannot parse the select_choices_or_calculations field from REDCap metadata. This may happen if there
  is a pipe character `|` inside the label: 1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour
  metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported

**Comment by ezraporter** [comment]
I think this is a genuine bug in how we parse the labels from the REDCap API. Based on the error message @camcaan's REDCap is returning:

```r
1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported
```

It looks like `parse_labels()` expects whitespace after the comma:

https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/d4a07208b068f4b57c6b6cb112c04d1bf3e6097e/R/utils.R#L136-L140

I think this should be easy to fix.

**Comment by skadauke** [comment]
Yes, we had a similar bug where parse_labels()​ expects whitespace around the pipe characters. Let's fix this and make sure to trim whitespace around the comma.

________________________________
From: ezraporter ***@***.***>
Sent: Tuesday, February 14, 2023 12:00 PM
To: CHOP-CGTInformatics/REDCapTidieR ***@***.***>
Cc: Stephan Kadauke ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [CHOP-CGTInformatics/REDCapTidieR] [BUG] (Issue #128)


I think this is a genuine bug in how we parse the labels from the REDCap API. Based on the error message @camcaan<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcamcaan&data=05%7C01%7Ckadaukes%40chop.edu%7C6fd3977b17174ce86f7d08db0eacf0c5%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119908168767124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FZSgfQoqrHX6So1qs0ToP7U%2FTr27bpiZzy1zjAJaoVA%3D&reserved=0>'s REDCap is returning:

1,leukaemia| 2,lymphoma| 3,solid tumour localised| 4,solid tumour metastasised| 666,Not Known| 777,Not Applicable|888, Not Done|999,Not Reported

It looks like parse_labels() expects whitespace after the comma:

https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/d4a07208b068f4b57c6b6cb112c04d1bf3e6097e/R/utils.R#L136-L140<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTInformatics%2FREDCapTidieR%2Fblob%2Fd4a07208b068f4b57c6b6cb112c04d1bf3e6097e%2FR%2Futils.R%23L136-L140&data=05%7C01%7Ckadaukes%40chop.edu%7C6fd3977b17174ce86f7d08db0eacf0c5%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119908168767124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MdbCbg7rUiHgqv1BOapVbIiOV6d3NAKmoTfjqGEp3ww%3D&reserved=0>

I think this should be easy to fix.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTInformatics%2FREDCapTidieR%2Fissues%2F128%23issuecomment-1430076283&data=05%7C01%7Ckadaukes%40chop.edu%7C6fd3977b17174ce86f7d08db0eacf0c5%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119908168767124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kxhC2MR8FmlkCMgCKKGXHJriGrKRGFYNyDdFO0K7fzY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWT6YVG627SZHDB7JZLWXO2ZXANCNFSM6AAAAAAU3S7XQA&data=05%7C01%7Ckadaukes%40chop.edu%7C6fd3977b17174ce86f7d08db0eacf0c5%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638119908168767124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yfGrg3p%2BagaVX%2BwddoFpdt8A99KAaV%2F%2FfI2zGBmVk94%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by ezraporter** [comment]
@camcaan this should now be fixed in the dev version on github. Let me know if the error is resolved once you download the latest.

**Comment by camcaan** [comment]
Yes, it worked perfectly. Thank you so much, Appreciated.

**Comment by camcaan** [comment]
It worked without any error but the data I have consists of more than 11000 rows and over 400 columns but after the REDCAptidieR import 
<img width="1087" alt="Screenshot 2023-02-14 at 20 42 07" src="https://user-images.githubusercontent.com/42880915/218859002-93e5ab39-f2fb-4336-9ada-61126cd01846.png">
I see only few data rows and variables in each tibble. Not sure whats the issue. I dont know if you can see the screenshot i uploaded above.

**Comment by camcaan** [comment]
sorry about my earlier message. I deleted it. the problem was in the url i used.
