### ISSUE TITLE
[FEATURE] Remove unknown licence

### ISSUE THREAD

**Issue by RhysPeploe** [CHOP-CGTInformatics/REDCapTidieR#171]
openjournals/joss-reviews#6277

# Feature Request Description
Two licences are featured, however, all the information in the 'unknown'/non-MIT license is incorparated into the MIT license so it would be simplier to have just the one licence (the MIT one) and remove the other to avoid confusion. Unless there is a good reason to keep the two in parallel.

![image](https://github.com/CHOP-CGTInformatics/REDCapTidieR/assets/68282471/db01fa5a-ea68-4559-937f-8dac8faa7cf5)

![image](https://github.com/CHOP-CGTInformatics/REDCapTidieR/assets/68282471/b361c391-ec07-444f-92e0-7c0ae93bdece)

### Checklist

- [X] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by skadauke** [comment]
Thanks Rhys. @rsh52 that seems easy enough to do!

**Comment by rsh52** [comment]
Hi @RhysPeploe and @skadauke, thanks for pointing this out. Before I remove, I notice this is common among some other high-profile packages:

- [`gtsummary`](https://github.com/ddsjoberg/gtsummary)
- [`dplyr`](https://github.com/tidyverse/dplyr)
- [`ggplot2`](https://github.com/tidyverse/ggplot2)

From what I recall, this is due to a standard `LICENSE` file (not `LICENSE.md` where the MIT one exists) when you develop an R package in the standard framework. This was part of the initial commit from the start of the repository, and gets added to the `DESCRIPTION` file as `License: MIT + file LICENSE`.

Let me know your thoughts.

**Comment by RhysPeploe** [comment]
Ah thank you for pointing this out, I hadn't noticed it elsewhere. Happy for you to keep it as is, I'll check this off the checklist

**Comment by rsh52** [comment]
> Ah thank you for pointing this out, I hadn't noticed it elsewhere. Happy for you to keep it as is, I'll check this off the checklist

Great! Thank you. Closing this now then.
