### ISSUE TITLE
Address deprecation warnings in GitHub Actions workflows

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTInformatics/REDCapTidieR#46]
# Description

Our Actions workflows began issuing warnings related to [this update](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) from GitHub.

![Screen Shot 2022-10-12 at 3 39 01 PM](https://user-images.githubusercontent.com/60618324/195432922-c5e8b6ee-a3ec-4642-adee-296ca2cf9433.png)

There's an open issue on r-lib/actions https://github.com/r-lib/actions/issues/627

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [ ] Labels are assigned to the issue

**Comment by skadauke** [comment]
Not sure we need to/should do anything about this? Once `r-lib/actions` is fixed, this warning should automagically go away for us, right?

**Comment by rsh52** [comment]
You're probably right, I was wondering if the fix would involve any changes to the actions callout (like `@v2` to `@v3`), but that likely wouldn't happen. Figured that since we have a warning returned from our Actions runs it would be worth documenting the reason why and then we can close this once the `r-lib` folks resolve it.

**Comment by skadauke** [comment]
Totally agree!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Rich Hanna ***@***.***>
Sent: Thursday, October 13, 2022 8:15:02 AM
To: CHOP-CGTDataOps/REDCapTidieR ***@***.***>
Cc: Stephan Kadauke ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [CHOP-CGTDataOps/REDCapTidieR] Address deprecation warnings in GitHub Actions workflows (Issue #46)


You're probably right, I was wondering if the fix would involve any changes to the actions callout (like @v2 to @v3), but that likely wouldn't happen. Figured that since we have a warning returned from our Actions runs it would be worth documenting the reason why and then we can close this once the r-lib folks resolve it.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTDataOps%2FREDCapTidieR%2Fissues%2F46%23issuecomment-1277516589&data=05%7C01%7Ckadaukes%40chop.edu%7Cc01c20abe914402f44ac08daad148ff3%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638012601067944225%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Aq4jPVuEDI19g9Fk84usY6E3NM3uwp36PvXVT3D2y2Q%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWW6A3BSTVX7UTVCPKDWC74MNANCNFSM6AAAAAARDTD75U&data=05%7C01%7Ckadaukes%40chop.edu%7Cc01c20abe914402f44ac08daad148ff3%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638012601067944225%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zdyeQ2o%2BCEaY6bSBQweM1HglezTLZgdRxNzSgDW7NOc%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by rsh52** [comment]
Update posted: https://github.com/r-lib/actions/issues/627#issuecomment-1283906528

**Comment by rsh52** [comment]
It looks like this has been resolved on our most recent commits/merges, but we're getting the below warning:
![image](https://user-images.githubusercontent.com/38384694/199022363-18e2f277-f10a-4935-8243-adcad7defd13.png)

Updating our workflow files to `@v3` should resolve this though, the actions files from [R-lib were update to use v16](https://github.com/r-lib/actions/blob/v2-branch/pr-push/action.yml).

**Comment by skadauke** [comment]
I think this got resolved? Can we close? @rsh52 @ezraporter

**Comment by rsh52** [comment]
Yea it looks like those are no longer appearing on the recent `pkgdown` actions workflows.
